language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "14"

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - adoa2705@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy of GITHUB Actions"
  on:
    branch: main
